name: starter_app
description: Flutter starter app

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #For StateManagement And Root
  freezed_annotation: ^1.1.0
  stacked: ^2.2.5
  stacked_services: ^0.8.13

  #External Api
  flutter_keyboard_visibility: any
  connectivity_plus: ^3.0.2
  package_info_plus: ^3.0.2
  dio: ^4.0.6

dev_dependencies:
  build_runner: ^2.0.4
  package_rename: ^1.0.0+1
  stacked_generator: ^0.5.2
  freezed: ^1.1.1
  assets_indexer: ^0.0.10

package_rename_config:
  android:
    app_name: StarterApp
    bundle_name: starterapp
    package_name: com.starter.app

  ios:
    app_name: StarterApp
    bundle_name: starterapp
    package_name: com.starter.app

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
