name: starter_app
description: Flutter starter app

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #For StateManagement And Root
  freezed_annotation: ^2.2.0
  stacked: ^3.4.1
  stacked_services: ^1.2.0
  intl: ^0.18.0
  get: ^4.6.5
  go_router: ^9.0.0

  #External Api
  flutter_keyboard_visibility: ^5.4.1
  connectivity_plus: ^4.0.1
  package_info_plus: ^4.0.2
  dio: ^5.2.1+1
  shared_preferences: ^2.2.0

  #For UI
  hexcolor: ^3.0.1
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4

dev_dependencies:
  build_runner: ^2.4.6
  stacked_generator: ^1.4.0
  freezed: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/