name: starter
description: Flutter starter app

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #For StateManagement And Root
  freezed_annotation: ^2.4.4
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  intl: ^0.20.1
  get: ^4.6.6
  go_router: ^14.6.3

  #External Api
  flutter_keyboard_visibility: ^6.0.0
  connectivity_plus: ^6.1.1
  package_info_plus: ^8.1.2
  dio: ^5.7.0
  shared_preferences: ^2.3.5

  #For UI
  hexcolor: ^3.0.1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  build_runner: ^2.4.14
  stacked_generator: ^1.6.1
  freezed: ^2.5.7
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/